export const COLOR_TOKEN_DEFINITIONS = [
  { token: 'background', label: 'Hintergrund' },
  { token: 'foreground', label: 'Text primär' },
  { token: 'text-secondary', label: 'Text sekundär' },
  { token: 'text-muted', label: 'Text gedämpft' },
  { token: 'card-background', label: 'Kartenfläche' },
  { token: 'card-border', label: 'Kartenrand' },
  { token: 'input-background', label: 'Eingabefläche' },
  { token: 'input-border', label: 'Eingaberand' },
  { token: 'form-background', label: 'Formularfläche' },
  { token: 'comment-background', label: 'Kommentarfläche' },
  { token: 'border-light', label: 'Trennlinien' },
  { token: 'accent', label: 'Akzent' },
  { token: 'accent-hover', label: 'Akzent Hover' },
  { token: 'accent-foreground', label: 'Akzent Text' },
  { token: 'danger', label: 'Gefahr' },
  { token: 'danger-foreground', label: 'Gefahr Text' },
  { token: 'error-background', label: 'Fehler Hintergrund' },
  { token: 'error-text', label: 'Fehler Text' },
  { token: 'status-open', label: 'Status Offen' },
  { token: 'status-in-progress', label: 'Status In Arbeit' },
  { token: 'status-in-discussion', label: 'Status Diskussion' },
  { token: 'status-completed', label: 'Status Erledigt' },
  { token: 'status-rejected', label: 'Status Abgelehnt' },
  { token: 'priority-low', label: 'Priorität Niedrig' },
  { token: 'priority-medium', label: 'Priorität Mittel' },
  { token: 'priority-high', label: 'Priorität Hoch' },
] as const;

export type ColorToken = typeof COLOR_TOKEN_DEFINITIONS[number]['token'];

export type ColorSchemeName = 'light' | 'dark' | 'msg' | 'high-contrast';

export const COLOR_SCHEME_OPTIONS: Array<{ value: ColorSchemeName; label: string }> = [
  { value: 'light', label: 'Standard' },
  { value: 'dark', label: 'Dunkel' },
  { value: 'msg', label: 'msg systems ag' },
  { value: 'high-contrast', label: 'Hoher Kontrast' },
];

const COLOR_TOKENS = COLOR_TOKEN_DEFINITIONS.map((entry) => entry.token) as ColorToken[];

export const COLOR_SCHEMES: Record<ColorSchemeName, Record<ColorToken, string>> = {
  light: {
    background: '#ffffff',
    foreground: '#171717',
    'card-background': '#ffffff',
    'card-border': '#dddddd',
    'input-border': '#dddddd',
    'input-background': '#ffffff',
    'text-muted': '#666666',
    'text-secondary': '#333333',
    'border-light': '#eeeeee',
    'form-background': '#f5f5f5',
    'comment-background': '#f9f9f9',
    accent: '#722f37',
    'accent-hover': '#5a252c',
    'accent-foreground': '#ffffff',
    'error-background': '#ffebee',
    'error-text': '#c62828',
    danger: '#f44336',
    'danger-foreground': '#ffffff',
    'status-open': '#4caf50',
    'status-in-progress': '#2196f3',
    'status-in-discussion': '#ffb300',
    'status-completed': '#9e9e9e',
    'status-rejected': '#f44336',
    'priority-low': '#8bc34a',
    'priority-medium': '#ff9800',
    'priority-high': '#f44336',
  },
  dark: {
    background: '#0a0a0a',
    foreground: '#ededed',
    'card-background': '#1a1a1a',
    'card-border': '#333333',
    'input-border': '#444444',
    'input-background': '#1a1a1a',
    'text-muted': '#999999',
    'text-secondary': '#cccccc',
    'border-light': '#333333',
    'form-background': '#1a1a1a',
    'comment-background': '#222222',
    accent: '#a04050',
    'accent-hover': '#8a3545',
    'accent-foreground': '#ffffff',
    'error-background': '#2d1a1a',
    'error-text': '#ff6b6b',
    danger: '#ff6b6b',
    'danger-foreground': '#ffffff',
    'status-open': '#4caf50',
    'status-in-progress': '#2196f3',
    'status-in-discussion': '#ffb300',
    'status-completed': '#9e9e9e',
    'status-rejected': '#ff6b6b',
    'priority-low': '#8bc34a',
    'priority-medium': '#ff9800',
    'priority-high': '#ff6b6b',
  },
  msg: {
    background: '#f8f8f8',
    foreground: '#131313',
    'card-background': '#ffffff',
    'card-border': '#e1e1e1',
    'input-border': '#d9d9d9',
    'input-background': '#ffffff',
    'text-muted': '#6f6f6f',
    'text-secondary': '#3e3e3e',
    'border-light': '#ededed',
    'form-background': '#f9f9f9',
    'comment-background': '#ffffff',
    accent: '#a01441',
    'accent-hover': '#7f0f32',
    'accent-foreground': '#ffffff',
    'error-background': '#fbeaec',
    'error-text': '#c62828',
    danger: '#d32f2f',
    'danger-foreground': '#ffffff',
    'status-open': '#4caf50',
    'status-in-progress': '#2196f3',
    'status-in-discussion': '#ffb300',
    'status-completed': '#9e9e9e',
    'status-rejected': '#d32f2f',
    'priority-low': '#8bc34a',
    'priority-medium': '#ff9800',
    'priority-high': '#d32f2f',
  },
  'high-contrast': {
    background: '#000000',
    foreground: '#ffffff',
    'card-background': '#000000',
    'card-border': '#ffffff',
    'input-border': '#ffffff',
    'input-background': '#000000',
    'text-muted': '#ffffff',
    'text-secondary': '#ffffff',
    'border-light': '#ffffff',
    'form-background': '#000000',
    'comment-background': '#000000',
    accent: '#ffff00',
    'accent-hover': '#ffd400',
    'accent-foreground': '#000000',
    'error-background': '#000000',
    'error-text': '#ff0000',
    danger: '#ff0000',
    'danger-foreground': '#ffffff',
    'status-open': '#00ff00',
    'status-in-progress': '#00b0ff',
    'status-in-discussion': '#ffb300',
    'status-completed': '#ffffff',
    'status-rejected': '#ff0000',
    'priority-low': '#00ff00',
    'priority-medium': '#ffb300',
    'priority-high': '#ff0000',
  },
};

const COLOR_VALUE_PATTERN = /^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/;
const COLOR_TOKEN_SET = new Set<ColorToken>(COLOR_TOKENS);

export const isColorToken = (value: string): value is ColorToken => COLOR_TOKEN_SET.has(value as ColorToken);

export const normalizeColorValue = (value: string): string | null => {
  const trimmed = value.trim();
  const match = COLOR_VALUE_PATTERN.exec(trimmed);
  if (!match) return null;
  const hex = match[1];
  const expanded = hex.length === 3 ? hex.split('').map((char) => char + char).join('') : hex;
  return `#${expanded.toLowerCase()}`;
};
